In [ ]:
# Predictors [2/3]

In [1]:
import pandas as pd

In [10]:
mvps = pd.read_csv("mvps.csv", index_col=0)

In [11]:
mvps

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,11,Russell Westbrook,32,WAS,0.0,5.0,1010,0.005,65,36.4,...,11.5,11.7,1.4,0.4,0.439,0.315,0.656,3.7,0.075,2021
11,12,Ben Simmons,24,PHI,0.0,3.0,1010,0.003,58,32.4,...,7.2,6.9,1.6,0.6,0.557,0.300,0.613,6.0,0.153,2021
12,13T,James Harden,31,TOT,0.0,1.0,1010,0.001,44,36.6,...,7.9,10.8,1.2,0.8,0.466,0.362,0.861,7.0,0.208,2021
13,13T,LeBron James,36,LAL,0.0,1.0,1010,0.001,45,33.4,...,7.7,7.8,1.1,0.6,0.513,0.365,0.698,5.6,0.179,2021
14,13T,Kawhi Leonard,29,LAC,0.0,1.0,1010,0.001,52,34.1,...,6.5,5.2,1.6,0.4,0.512,0.398,0.885,8.8,0.238,2021

In [14]:
players = pd.read_csv("players.csv", index_col=0)

In [15]:
players

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,2,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,3,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,4,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,5,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,536,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
726,537,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
727,538,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
728,539,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
729,540,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021

In [16]:
del players["Rk"]

In [19]:
players["Player"] = players["Player"].str.replace("*","", regex=False)
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

In [52]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,DEN,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
8,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
10,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
9,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
8,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
10,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
8,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [21]:
def single_team(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Tm"]=="TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

players = players.groupby(["Player", "Year"]).apply(single_team)

In [22]:
players

                                 Player Pos Age   Tm   G  GS    MP   FG   FGA  \
Player         Year
A.C. Green     1991 164      A.C. Green  PF  27  LAL  82  21  26.4  3.1   6.6
               1992 174      A.C. Green  PF  28  LAL  82  53  35.4  4.7   9.8
               1993 157      A.C. Green  PF  29  LAL  82  55  34.4  4.6   8.6
               1994 177      A.C. Green  PF  30  PHO  82  55  34.5  5.7  11.3
               1995 165      A.C. Green  SF  31  PHO  82  52  32.8  3.8   7.5
...                                 ...  ..  ..  ...  ..  ..   ...  ...   ...
Željko Rebrača 2002 394  Željko Rebrača   C  29  DET  74   4  15.9  2.6   5.1
               2003 374  Željko Rebrača   C  30  DET  30  12  16.3  2.7   4.8
               2004 452  Željko Rebrača   C  31  ATL  24   2  11.4  1.4   3.2
               2005 446  Željko Rebrača   C  32  LAC  58   2  16.0  2.3   4.0
               2006 433  Željko Rebrača   C  33  LAC  29   2  14.2  1.8   3.3

                          FG%  ...  ORB  DRB  TRB  AST  STL  BLK  TOV   PF  \
Player         Year            ...
A.C. Green     1991 164  .476  ...  2.5  3.8  6.3  0.9  0.7  0.3  1.2  1.4
               1992 174  .476  ...  3.7  5.6  9.3  1.4  1.1  0.4  1.4  1.7
               1993 157  .537  ...  3.5  5.2  8.7  1.4  1.1  0.5  1.4  1.8
               1994 177  .502  ...  3.4  5.8  9.2  1.7  0.9  0.5  1.2  1.7
               1995 165  .504  ...  2.4  5.8  8.2  1.5  0.7  0.4  1.4  1.8
...                       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
Željko Rebrača 2002 394  .505  ...  1.1  2.8  3.9  0.5  0.4  1.0  1.1  2.6
               2003 374  .552  ...  0.9  2.2  3.1  0.3  0.2  0.6  1.0  2.6
               2004 452  .442  ...  1.0  1.5  2.4  0.3  0.2  0.5  0.7  2.2
               2005 446  .568  ...  0.8  2.3  3.2  0.4  0.2  0.7  0.8  2.2
               2006 433  .542  ...  0.4  1.8  2.2  0.3  0.2  0.7  0.8  2.0

                          PTS  Year
Player         Year
A.C. Green     1991 164   9.1  1991
               1992 174  13.6  1992
               1993 157  12.8  1993
               1994 177  14.7  1994
               1995 165  11.2  1995
...                       ...   ...
Željko Rebrača 2002 394   6.9  2002
               2003 374   6.6  2003
               2004 452   3.8  2004
               2005 446   5.8  2005
               2006 433   4.7  2006

[14092 rows x 30 columns]

In [24]:
players.index = players.index.droplevel()

In [26]:
players.head()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
164,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,2.5,3.8,6.3,0.9,0.7,0.3,1.2,1.4,9.1,1991
174,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,3.7,5.6,9.3,1.4,1.1,0.4,1.4,1.7,13.6,1992
157,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,3.5,5.2,8.7,1.4,1.1,0.5,1.4,1.8,12.8,1993
177,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,3.4,5.8,9.2,1.7,0.9,0.5,1.2,1.7,14.7,1994
165,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,2.4,5.8,8.2,1.5,0.7,0.4,1.4,1.8,11.2,1995

In [28]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,DEN,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
8,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
10,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
9,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
8,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
10,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
8,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [55]:
combined = players.merge(mvps, how="outer", on=["Player", "Year"])

In [56]:
combined[combined['Pts Won']>0]

,Player,Pos,Age_x,Tm_x,G_x,GS,MP_x,FG,FGA,FG%_x,...,PTS_y,TRB_y,AST_y,STL_y,BLK_y,FG%_y,3P%_y,FT%_y,WS,WS/48
187,Al Jefferson,C,29,CHA,73,73,35.0,9.6,18.8,.509,...,21.8,10.8,2.1,0.9,1.1,0.509,0.200,0.690,7.8,0.146
329,Allen Iverson,PG,21,PHI,76,74,40.1,8.2,19.8,.416,...,23.5,4.1,7.5,2.1,0.3,0.416,0.341,0.702,4.1,0.065
331,Allen Iverson,SG,23,PHI,48,48,41.5,9.1,22.0,.412,...,26.8,4.9,4.6,2.3,0.1,0.412,0.291,0.751,7.2,0.173
332,Allen Iverson,SG,24,PHI,70,70,40.8,10.4,24.8,.421,...,28.4,3.8,4.7,2.1,0.1,0.421,0.341,0.713,6.9,0.116
333,Allen Iverson,SG,25,PHI,71,71,42.0,10.7,25.5,.420,...,31.1,3.8,4.6,2.5,0.3,0.420,0.320,0.814,11.8,0.190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13587,Vince Carter,SF,23,TOR,82,82,38.1,9.6,20.7,.465,...,25.7,5.8,3.9,1.3,1.1,0.465,0.403,0.791,11.8,0.182
13588,Vince Carter,SF,24,TOR,75,75,39.7,10.2,22.1,.460,...,27.6,5.5,3.9,1.5,1.1,0.460,0.408,0.765,12.9,0.208
13592,Vince Carter,SF-SG,28,NJN,77,76,36.7,9.0,20.0,.452,...,24.5,5.2,4.2,1.4,0.6,0.452,0.406,0.798,9.4,0.159
13952,Yao Ming,C,23,HOU,82,82,32.8,6.5,12.5,.522,...,17.5,9.0,1.5,0.3,1.9,0.522,0.000,0.809,11.4,0.202
13957,Yao Ming,C,28,HOU,77,77,33.6,7.4,13.4,.548,...,19.7,9.9,1.8,0.4,1.9,0.548,1.000,0.866,10.6,0.196

In [35]:
combined[["Pts Won", "Pts Max", "Share"]] = combined[["Pts Won", "Pts Max", "Share"]].fillna(0)

In [42]:
combined.columns

Index(['Player', 'Pos', 'Age_x', 'Tm_x', 'G_x', 'GS', 'MP_x', 'FG', 'FGA',
       'FG%_x', '3P', '3PA', '3P%_x', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%_x', 'ORB', 'DRB', 'TRB_x', 'AST_x', 'STL_x', 'BLK_x', 'TOV', 'PF',
       'PTS_x', 'Year', 'Rank', 'Age_y', 'Tm_y', 'First', 'Pts Won', 'Pts Max',
       'Share', 'G_y', 'MP_y', 'PTS_y', 'TRB_y', 'AST_y', 'STL_y', 'BLK_y',
       'FG%_y', '3P%_y', 'FT%_y', 'WS', 'WS/48'],
      dtype='object')

In [38]:
teams = pd.read_csv("teams.csv")
teams

,Unnamed: 0,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
...,...,...,...,...,...,...,...,...,...,...
1028,13,42,30,.583,—,112.4,110.2,2.26,2021,Dallas Mavericks*
1029,14,38,34,.528,4.0,113.3,112.3,1.07,2021,Memphis Grizzlies*
1030,15,33,39,.458,9.0,111.1,112.8,-1.58,2021,San Antonio Spurs
1031,16,31,41,.431,11.0,114.6,114.9,-0.20,2021,New Orleans Pelicans
1032,17,17,55,.236,25.0,108.8,116.7,-7.50,2021,Houston Rockets

In [39]:
teams = teams[~teams["W"].str.contains("Division")].copy()
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)
sorted(teams["Team"].unique())

['Atlanta Hawks',
 'Boston Celtics',
 'Brooklyn Nets',
 'Charlotte Bobcats',
 'Charlotte Hornets',
 'Chicago Bulls',
 'Cleveland Cavaliers',
 'Dallas Mavericks',
 'Denver Nuggets',
 'Detroit Pistons',
 'Golden State Warriors',
 'Houston Rockets',
 'Indiana Pacers',
 'Los Angeles Clippers',
 'Los Angeles Lakers',
 'Memphis Grizzlies',
 'Miami Heat',
 'Milwaukee Bucks',
 'Minnesota Timberwolves',
 'New Jersey Nets',
 'New Orleans Hornets',
 'New Orleans Pelicans',
 'New Orleans/Oklahoma City Hornets',
 'New York Knicks',
 'Oklahoma City Thunder',
 'Orlando Magic',
 'Philadelphia 76ers',
 'Phoenix Suns',
 'Portland Trail Blazers',
 'Sacramento Kings',
 'San Antonio Spurs',
 'Seattle SuperSonics',
 'Toronto Raptors',
 'Utah Jazz',
 'Vancouver Grizzlies',
 'Washington Bullets',
 'Washington Wizards']

In [57]:
sorted(combined["Tm"].unique())

KeyError: 'Tm'

In [46]:
nicknames = {}
with open("nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev,name = line.replace("\n","").split(",")
        nicknames[abbrev] = name

In [49]:
combined['Team'] = combined["Tm"].map(nicknames)

KeyError: 'Tm'

In [51]:
combined.head()

,Player,Pos,Age_x,Tm_x,G_x,GS,MP_x,FG,FGA,FG%_x,...,PTS_y,TRB_y,AST_y,STL_y,BLK_y,FG%_y,3P%_y,FT%_y,WS,WS/48
0,A.C. Green,PF,27,LAL,82,21,26.4,3.1,6.6,.476,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A.C. Green,PF,28,LAL,82,53,35.4,4.7,9.8,.476,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A.C. Green,PF,29,LAL,82,55,34.4,4.6,8.6,.537,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A.C. Green,PF,30,PHO,82,55,34.5,5.7,11.3,.502,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A.C. Green,SF,31,PHO,82,52,32.8,3.8,7.5,.504,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
train = combined.merge(teams, how="outer",on=["Team", "Year"])
train = train.apply(pd.to_numeric, errors='ignore')
train = train.apply(pd.to_numeric, errors='ignore')

KeyError: 'Team'

In [61]:
train = train.apply(pd.to_numeric, errors='ignore')

NameError: name 'train' is not defined

In [62]:
train["GB"] = pd.to_numeric(train["GB"].str.replace("—","0"))

NameError: name 'train' is not defined

In [63]:
train.to_csv("player_mvp_stats.csv")
highest_scoring = train[train["G"] > 70].sort_values("PTS", ascending=False).head(10)

NameError: name 'train' is not defined

In [64]:
highest_scoring.plot.bar("Player", "PTS")

NameError: name 'highest_scoring' is not defined

In [65]:
highest_scoring_by_year = train.groupby("Year").apply(lambda x: x.sort_values("PTS", ascending=False).head(1))
highest_scoring_by_year.plot.bar("Year", "PTS")

NameError: name 'train' is not defined

In [ ]:
train.groupby("Year").apply(lambda x: x.shape[0])

In [ ]:
train.corr()["Share"]

In [ ]:
train.corr()["Share"].plot.bar()